spring:
  application:
    name: cli-generator
  main:
    banner-mode: off

# cli工具配置
generator:
  cli:
    # cli工具名称
    name: "my-cli"

    # cli工具版本
    version: "0.0.1"

    # cli工具描述
    description: "我的cli命令行工具"

    # cli工具git代码仓库
    repo: "https://git.woa.com/larkzhang/cli-generator.git"

    # cli工具作者
    author: "larkzhang <larkzhang@tencent.com>"

    # cli工具开源协议
    license: "MIT"

    # cli工具可执行名称（包含别名）
    bin:
      - my-tool
      - mtool
      - mtl

    # 子命令
    commands:
        # 子命令名称
      - name: "list"
        # 子命令描述
        description: "列表查询"
        # 子命令主函数
        action: "listAction"
        # 子命令参数
        options:
            # 参数定义 （参考commander的option写法：https://github.com/tj/commander.js/blob/master/Readme_zh-CN.md#%e9%80%89%e9%a1%b9）
          - flags: "-cp, --client-port <port>"
            # 参数描述
            description: "指定PC端口"
            # 参数回调（预处理参数，可选）
            callback: "callbackFunc1"
            # 参数默认值（可选）
            value: "8765"

          - flags: "-sp, --server-port <port>"
            description: "指定测试机端口"

      - name: "record"
        description: "开始录制"
        action: "recordAction"
        options:
          - flags: "-o, --output <file>"
            description: "指定录制输出"

    # 全局参数
    options:
      - flags: "-a --all"
        description: "指定全部"
        callback: "callbackFunc2"